
/**************************************************************
 *	
 *	badApple, 8 bit, 11025Hz,
 *	1 channel, 8958 bytes/channel
 *	Total Size: 1 * 8958 + 4 (header) = 9002 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/lixin/Documents/CS2261/LixinWang_FinalProject/sounds/badApple.wav
 *	Time-stamp: Mon Dec 05 19:18:50 2016
 *	
 **************************************************************/

#ifndef __BADAPPLEH__
#define __BADAPPLEH__

#define BADAPPLEFREQ 11025
#define BADAPPLELEN 8958

extern const unsigned char badApple[8958];

#endif /* __BADAPPLEH__ */
