
/**************************************************************
 *	
 *	endSong, 8 bit, 11025Hz,
 *	1 channel, 190080 bytes/channel
 *	Total Size: 1 * 190080 + 4 (header) = 190124 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/lixin/Documents/CS2261/LixinWang_FinalProject/sounds/endSong.wav
 *	Time-stamp: Tue Dec 13 19:34:11 2016
 *	
 **************************************************************/

#ifndef __ENDSONGH__
#define __ENDSONGH__

#define ENDSONGFREQ 11025
#define ENDSONGLEN 190080

extern const unsigned char endSong[190080];

#endif /* __ENDSONGH__ */
