
/**************************************************************
 *	
 *	gainLifeSFX, 8 bit, 11025Hz,
 *	1 channel, 2940 bytes/channel
 *	Total Size: 1 * 2940 + 4 (header) = 2984 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/lixin/Documents/CS2261/LixinWang_FinalProject/sounds/gainLifeSFX.wav
 *	Time-stamp: Mon Dec 05 21:25:34 2016
 *	
 **************************************************************/

#ifndef __GAINLIFESFXH__
#define __GAINLIFESFXH__

#define GAINLIFESFXFREQ 11025
#define GAINLIFESFXLEN 2940

extern const unsigned char gainLifeSFX[2940];

#endif /* __GAINLIFESFXH__ */
