
/**************************************************************
 *	
 *	gameSong, 8 bit, 11025Hz,
 *	1 channel, 841536 bytes/channel
 *	Total Size: 1 * 841536 + 4 (header) = 841580 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/lixin/Documents/CS2261/LixinWang_FinalProject/sounds/gameSong.wav
 *	Time-stamp: Mon Dec 05 18:51:34 2016
 *	
 **************************************************************/

#ifndef __GAMESONGH__
#define __GAMESONGH__

#define GAMESONGFREQ 11025
#define GAMESONGLEN 841536

extern const unsigned char gameSong[841536];

#endif /* __GAMESONGH__ */
