
/**************************************************************
 *	
 *	shrink, 8 bit, 11025Hz,
 *	1 channel, 6095 bytes/channel
 *	Total Size: 1 * 6095 + 4 (header) = 6139 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/lixin/Documents/CS2261/LixinWang_FinalProject/sounds/shrink.wav
 *	Time-stamp: Mon Dec 05 19:26:12 2016
 *	
 **************************************************************/

#ifndef __SHRINKH__
#define __SHRINKH__

#define SHRINKFREQ 11025
#define SHRINKLEN 6095

extern const unsigned char shrink[6095];

#endif /* __SHRINKH__ */
