
/**************************************************************
 *	
 *	collectApple, 8 bit, 11025Hz,
 *	1 channel, 1848 bytes/channel
 *	Total Size: 1 * 1848 + 4 (header) = 1892 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/lixin/Documents/CS2261/LixinWang_FinalProject/sounds/collectApple.wav
 *	Time-stamp: Mon Dec 05 19:18:34 2016
 *	
 **************************************************************/

#ifndef __COLLECTAPPLEH__
#define __COLLECTAPPLEH__

#define COLLECTAPPLEFREQ 11025
#define COLLECTAPPLELEN 1848

extern const unsigned char collectApple[1848];

#endif /* __COLLECTAPPLEH__ */
