
/**************************************************************
 *	
 *	grow, 8 bit, 11025Hz,
 *	1 channel, 4410 bytes/channel
 *	Total Size: 1 * 4410 + 4 (header) = 4454 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/lixin/Documents/CS2261/LixinWang_FinalProject/sounds/grow.wav
 *	Time-stamp: Mon Dec 05 19:25:59 2016
 *	
 **************************************************************/

#ifndef __GROWH__
#define __GROWH__

#define GROWFREQ 11025
#define GROWLEN 4410

extern const unsigned char grow[4410];

#endif /* __GROWH__ */
