
/**************************************************************
 *	
 *	instructSong, 8 bit, 11025Hz,
 *	1 channel, 555552 bytes/channel
 *	Total Size: 1 * 555552 + 4 (header) = 555596 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/lixin/Documents/CS2261/LixinWang_FinalProject/sounds/instructSong.wav
 *	Time-stamp: Mon Dec 05 18:51:19 2016
 *	
 **************************************************************/

#ifndef __INSTRUCTSONGH__
#define __INSTRUCTSONGH__

#define INSTRUCTSONGFREQ 11025
#define INSTRUCTSONGLEN 555552

extern const unsigned char instructSong[555552];

#endif /* __INSTRUCTSONGH__ */
