
/**************************************************************
 *	
 *	makePie, 8 bit, 11025Hz,
 *	1 channel, 12173 bytes/channel
 *	Total Size: 1 * 12173 + 4 (header) = 12217 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/lixin/Documents/CS2261/LixinWang_FinalProject/sounds/makePie.wav
 *	Time-stamp: Mon Dec 05 19:26:28 2016
 *	
 **************************************************************/

#ifndef __MAKEPIEH__
#define __MAKEPIEH__

#define MAKEPIEFREQ 11025
#define MAKEPIELEN 12173

extern const unsigned char makePie[12173];

#endif /* __MAKEPIEH__ */
