
/**************************************************************
 *	
 *	menuSong, 8 bit, 11025Hz,
 *	1 channel, 1289088 bytes/channel
 *	Total Size: 1 * 1289088 + 4 (header) = 1289132 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/lixin/Documents/CS2261/LixinWang_FinalProject/sounds/menuSong.wav
 *	Time-stamp: Mon Dec 05 18:50:57 2016
 *	
 **************************************************************/

#ifndef __MENUSONGH__
#define __MENUSONGH__

#define MENUSONGFREQ 11025
#define MENUSONGLEN 1289088

extern const unsigned char menuSong[1289088];

#endif /* __MENUSONGH__ */
